# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:13.6.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: Lint and Test
          command: |
            mkdir -p ~/reports
            npm run lint -- --format junit --output-file ~/reports/eslint.xml
            npm run test:coverage:unit -- --ci --coverageDirectory ~/reports/unit
            npm run test:coverage:integration -- --ci --coverageDirectory ~/reports/integration
      - run:
          name: Send Code Coverage Report
          command: |
            npx codecov -F unit -f ~/reports/unit/*
            npx codecov -F integration -f ~/reports/integration/*
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

      

      